# Generated by Django 4.1 on 2022-12-05 21:22

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_name', models.CharField(max_length=100, null=True, verbose_name='Reference Name')),
                ('reference_image', models.ImageField(null=True, upload_to='image/references/', verbose_name='Reference Image')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('image', models.ImageField(null=True, upload_to='image/')),
                ('publishing_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Yayınlanma Tarihi')),
                ('completed', models.CharField(choices=[('completed', 'completed'), ('draft', 'draft')], default='completed', max_length=200)),
                ('body', ckeditor.fields.RichTextField(null=True)),
                ('slug', models.SlugField(editable=False, null=True, unique=True)),
                ('date', models.DateTimeField(default='2022')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
