# Generated by Django 4.1 on 2022-12-05 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy_web', '0003_alter_news_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.CharField(default='2022Aralık', editable=False, max_length=200),
        ),
    ]
