# Generated by Django 4.1 on 2022-12-05 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy_web', '0008_alter_news_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200, null=True, verbose_name='Name')),
                ('Subject', models.CharField(max_length=200, null=True, verbose_name='Name')),
                ('Content', models.TextField(max_length=2500, null=True, verbose_name='Content')),
                ('mail', models.EmailField(max_length=100, null=True)),
                ('tel', models.CharField(max_length=12, null=True, verbose_name='telefon')),
            ],
        ),
    ]
