# Generated by Django 3.2.15 on 2022-12-06 00:28

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy_web', '0009_connection'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_image', models.ImageField(null=True, upload_to='image/')),
                ('about_text', ckeditor.fields.RichTextField(null=True)),
                ('detail_image', models.ImageField(null=True, upload_to='image/')),
                ('detail_text_1', models.CharField(max_length=700, null=True, verbose_name='Name')),
                ('detail_text_2', models.CharField(max_length=700, null=True, verbose_name='Name')),
                ('detail_text_3', models.CharField(max_length=700, null=True, verbose_name='Name')),
                ('detail_text_4', models.CharField(max_length=700, null=True, verbose_name='Name')),
            ],
        ),
    ]
