# Generated by Django 4.1 on 2022-12-06 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy_web', '0011_team_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team_member',
            name='instangram_link',
        ),
        migrations.AddField(
            model_name='team_member',
            name='instagram_link',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
