# Generated by Django 4.1 on 2022-12-06 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy_web', '0012_remove_team_member_instangram_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='date_for_news',
            field=models.CharField(default='6 Aralık 2022', editable=False, max_length=200),
        ),
    ]
