# Generated by Django 4.1 on 2022-12-06 09:00

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy_web', '0013_news_date_for_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='summary',
            field=ckeditor.fields.RichTextField(default='abc', null=True),
        ),
    ]
