# Generated by Django 4.1 on 2022-12-06 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy_web', '0015_alter_news_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='summary',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
