# Generated by Django 4.1 on 2022-12-06 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy_web', '0018_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(editable=False, null=True, unique=True),
        ),
    ]
