# Generated by Django 4.1 on 2023-01-08 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy_web', '0020_product_publishing_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.CharField(default='Ocak 2023', editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='news',
            name='date_for_news',
            field=models.CharField(default='8 Ocak 2023', editable=False, max_length=200),
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Name - Surname')),
                ('email', models.CharField(max_length=150, null=True, verbose_name='Email')),
                ('content', models.TextField(max_length=500, null=True, verbose_name='Comment')),
                ('publishing_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Yayınlanma Tarihi')),
                ('date_for_news', models.CharField(default='8.1.2023', editable=False, max_length=200)),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='galaxy_web.news')),
            ],
            options={
                'ordering': ['-publishing_date', 'id'],
            },
        ),
    ]
