# Generated by Django 4.1 on 2023-01-08 19:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy_web', '0021_alter_news_date_alter_news_date_for_news_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cover_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(null=True, upload_to='image/cover/')),
                ('image2', models.ImageField(null=True, upload_to='image/cover/')),
                ('image3', models.ImageField(null=True, upload_to='image/cover/')),
            ],
        ),
        migrations.CreateModel(
            name='Discount_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('image3', models.ImageField(null=True, upload_to='image/cover/')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Product', to='galaxy_web.product')),
            ],
        ),
    ]
