# Generated by Django 4.1 on 2023-01-08 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy_web', '0022_cover_image_discount_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount_product',
            name='image3',
        ),
        migrations.AddField(
            model_name='discount_product',
            name='duration',
            field=models.DurationField(null=True),
        ),
    ]
