# Generated by Django 4.1 on 2023-01-08 20:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy_web', '0024_remove_discount_product_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount_product',
            name='hour',
        ),
        migrations.RemoveField(
            model_name='discount_product',
            name='minute',
        ),
        migrations.AddField(
            model_name='discount_product',
            name='due_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='discount_product',
            name='month',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AddField(
            model_name='discount_product',
            name='year',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='discount_product',
            name='day',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(31)]),
        ),
        migrations.AlterField(
            model_name='discount_product',
            name='discount',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(2023)]),
        ),
    ]
