# Generated by Django 4.1 on 2023-01-08 20:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy_web', '0025_remove_discount_product_hour_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount_product',
            name='day',
        ),
        migrations.RemoveField(
            model_name='discount_product',
            name='month',
        ),
        migrations.RemoveField(
            model_name='discount_product',
            name='year',
        ),
        migrations.AlterField(
            model_name='discount_product',
            name='discount',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
