# Generated by Django 4.1 on 2023-01-09 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy_web', '0026_remove_discount_product_day_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='News_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Category Name')),
            ],
        ),
        migrations.AlterField(
            model_name='comments',
            name='date_for_news',
            field=models.CharField(default='10.1.2023', editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='news',
            name='date_for_news',
            field=models.CharField(default='10 Ocak 2023', editable=False, max_length=200),
        ),
        migrations.AddField(
            model_name='news',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Category', to='galaxy_web.news_category'),
        ),
    ]
