# Generated by Django 4.1 on 2023-01-11 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy_web', '0027_news_category_alter_comments_date_for_news_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='detail_text_1',
            field=models.CharField(max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='detail_text_2',
            field=models.CharField(max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='detail_text_3',
            field=models.CharField(max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='detail_text_4',
            field=models.CharField(max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='comments',
            name='date_for_news',
            field=models.CharField(default='11.1.2023', editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='connection',
            name='Name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='connection',
            name='Subject',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='date_for_news',
            field=models.CharField(default='11 Ocak 2023', editable=False, max_length=200),
        ),
    ]
