# Generated by Django 4.1 on 2023-01-11 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy_web', '0028_alter_about_detail_text_1_alter_about_detail_text_2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bulk_Order_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='The_Product', to='galaxy_web.product')),
            ],
        ),
    ]
