# Generated by Django 4.1.5 on 2023-01-23 22:19

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy_web', '0029_bulk_order_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='About_en',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_image', models.ImageField(null=True, upload_to='image/')),
                ('about_text', ckeditor.fields.RichTextField(null=True)),
                ('detail_image', models.ImageField(null=True, upload_to='image/')),
                ('detail_text_1', models.CharField(max_length=700, null=True)),
                ('detail_text_2', models.CharField(max_length=700, null=True)),
                ('detail_text_3', models.CharField(max_length=700, null=True)),
                ('detail_text_4', models.CharField(max_length=700, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='comments',
            name='date_for_news',
            field=models.CharField(default='24.1.2023', editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='news',
            name='date_for_news',
            field=models.CharField(default='24 Ocak 2023', editable=False, max_length=200),
        ),
    ]
