# Generated by Django 4.1.5 on 2023-01-14 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy_web', '0029_bulk_order_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='date_for_news',
            field=models.CharField(default='14.1.2023', editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='news',
            name='date_for_news',
            field=models.CharField(default='14 Ocak 2023', editable=False, max_length=200),
        ),
    ]
