# Generated by Django 4.1.5 on 2023-01-23 22:31

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy_web', '0030_about_en_alter_comments_date_for_news_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_en',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='image/products/')),
                ('name', models.CharField(max_length=100, null=True)),
                ('amount', models.CharField(max_length=100, null=True)),
                ('price', models.PositiveIntegerField(null=True)),
                ('description', ckeditor.fields.RichTextField(null=True)),
                ('category', models.CharField(default='Nargile kömürü', max_length=100, null=True)),
                ('slug', models.SlugField(editable=False, null=True, unique=True)),
                ('publishing_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Yayınlanma Tarihi')),
            ],
        ),
        migrations.CreateModel(
            name='Team_Member_en',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='image/')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Member Name')),
                ('position', models.CharField(max_length=100, null=True, verbose_name='Member Position')),
                ('facebook_link', models.CharField(blank=True, max_length=150, null=True)),
                ('instagram_link', models.CharField(blank=True, max_length=150, null=True)),
                ('twitter_link', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
    ]
