# Generated by Django 4.1.5 on 2023-01-23 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy_web', '0031_product_en_team_member_en'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product_en',
        ),
    ]
