# Generated by Django 4.1.5 on 2023-01-23 23:55

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('galaxy_web', '0032_delete_product_en'),
    ]

    operations = [
        migrations.CreateModel(
            name='News_Category_en',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Category Name')),
            ],
        ),
        migrations.CreateModel(
            name='News_en',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('image', models.ImageField(null=True, upload_to='image/')),
                ('publishing_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Yayınlanma Tarihi')),
                ('completed', models.CharField(choices=[('completed', 'completed'), ('draft', 'draft')], default='completed', max_length=200)),
                ('summary', models.CharField(max_length=500, null=True)),
                ('content', ckeditor.fields.RichTextField(null=True)),
                ('slug', models.SlugField(editable=False, null=True, unique=True)),
                ('date', models.CharField(default='January 2023', editable=False, max_length=200)),
                ('date_for_news', models.CharField(default='24 January 2023', editable=False, max_length=200)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Category', to='galaxy_web.news_category_en')),
            ],
        ),
    ]
