# Generated by Django 4.1.5 on 2023-01-24 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy_web', '0036_bulk_order_product_en'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount_product_en',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Productt', to='galaxy_web.product_en'),
        ),
    ]
