# Generated by Django 4.1.5 on 2023-01-24 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy_web', '0037_alter_discount_product_en_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments_en',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Name - Surname')),
                ('email', models.CharField(max_length=150, null=True, verbose_name='Email')),
                ('content', models.TextField(max_length=500, null=True, verbose_name='Comment')),
                ('publishing_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Yayınlanma Tarihi')),
                ('date_for_news', models.CharField(default='24.1.2023', editable=False, max_length=200)),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commentss', to='galaxy_web.news_en')),
            ],
            options={
                'ordering': ['-publishing_date', 'id'],
            },
        ),
    ]
