# Generated by Django 4.1.5 on 2023-01-24 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy_web', '0038_comments_en'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments_en',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='galaxy_web.news_en'),
        ),
    ]
