# Generated by Django 3.2.15 on 2023-01-24 17:22

from django.db import migrations, models
import galaxy_web.models


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy_web', '0039_alter_comments_en_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='about_image',
            field=models.ImageField(null=True, upload_to='image/', validators=[galaxy_web.models.file_size]),
        ),
        migrations.AlterField(
            model_name='about',
            name='detail_image',
            field=models.ImageField(null=True, upload_to='image/', validators=[galaxy_web.models.file_size]),
        ),
        migrations.AlterField(
            model_name='about_en',
            name='about_image',
            field=models.ImageField(null=True, upload_to='image/', validators=[galaxy_web.models.file_size]),
        ),
        migrations.AlterField(
            model_name='about_en',
            name='detail_image',
            field=models.ImageField(null=True, upload_to='image/', validators=[galaxy_web.models.file_size]),
        ),
        migrations.AlterField(
            model_name='cover_image',
            name='image1',
            field=models.ImageField(null=True, upload_to='image/cover/', validators=[galaxy_web.models.file_size]),
        ),
        migrations.AlterField(
            model_name='cover_image',
            name='image2',
            field=models.ImageField(null=True, upload_to='image/cover/', validators=[galaxy_web.models.file_size]),
        ),
        migrations.AlterField(
            model_name='cover_image',
            name='image3',
            field=models.ImageField(null=True, upload_to='image/cover/', validators=[galaxy_web.models.file_size]),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(null=True, upload_to='image/', validators=[galaxy_web.models.file_size]),
        ),
        migrations.AlterField(
            model_name='news_en',
            name='image',
            field=models.ImageField(null=True, upload_to='image/', validators=[galaxy_web.models.file_size]),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to='image/products/', validators=[galaxy_web.models.file_size]),
        ),
        migrations.AlterField(
            model_name='product_en',
            name='image',
            field=models.ImageField(null=True, upload_to='image/products/', validators=[galaxy_web.models.file_size]),
        ),
        migrations.AlterField(
            model_name='team_member',
            name='image',
            field=models.ImageField(null=True, upload_to='image/', validators=[galaxy_web.models.file_size]),
        ),
        migrations.AlterField(
            model_name='team_member_en',
            name='image',
            field=models.ImageField(null=True, upload_to='image/', validators=[galaxy_web.models.file_size]),
        ),
    ]
