# Generated by Django 4.1.5 on 2023-01-25 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy_web', '0040_auto_20230124_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='date_for_news',
            field=models.CharField(default='25.1.2023', editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='comments_en',
            name='date_for_news',
            field=models.CharField(default='25.1.2023', editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='news',
            name='date_for_news',
            field=models.CharField(default='25 Ocak 2023', editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(null=True, upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='news_en',
            name='date_for_news',
            field=models.CharField(default='25 January 2023', editable=False, max_length=200),
        ),
    ]
