# Generated by Django 4.1.5 on 2023-01-25 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy_web', '0041_alter_comments_date_for_news_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(null=True, upload_to='media/image/'),
        ),
    ]
