# Generated by Django 4.0.3 on 2023-02-11 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy_web', '0043_alter_news_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='date_for_news',
            field=models.CharField(default='11.2.2023', editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='comments_en',
            name='date_for_news',
            field=models.CharField(default='11.2.2023', editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.CharField(default='Şubat 2023', editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='news',
            name='date_for_news',
            field=models.CharField(default='11 Şubat 2023', editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='news_en',
            name='date',
            field=models.CharField(default='Februay 2023', editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='news_en',
            name='date_for_news',
            field=models.CharField(default='11 Februay 2023', editable=False, max_length=200),
        ),
    ]
