# Generated by Django 4.0.3 on 2023-08-05 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy_web', '0044_alter_comments_date_for_news_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='date_for_news',
            field=models.CharField(default='6.8.2023', editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='comments_en',
            name='date_for_news',
            field=models.CharField(default='6.8.2023', editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.CharField(default='Ağustos 2023', editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='news',
            name='date_for_news',
            field=models.CharField(default='6 Ağustos 2023', editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='news_en',
            name='date',
            field=models.CharField(default='August 2023', editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='news_en',
            name='date_for_news',
            field=models.CharField(default='6 August 2023', editable=False, max_length=200),
        ),
    ]
